// Module included in the following assemblies:
//
// * docs/vs-code-extension-guide/master.adoc

[id='vscode-extension-reviewing-projects_{context}']

= Reviewing issues with the {ProductName} extension




The *MTA Report* is an HTML report generated by the MTA plugin that opens in your browser. From the report landing page you can navigate to detailed reports, such as Application Details, Issues, and Dependencies. The report is described in detail in link:{ProductDocUserGuideURL}/index#review_reports_cli-guide[{ProductShortName} Report].

Look at A's

+
Clicking on an issue reveals detailed information about a selected issue, including the hint and any additional resources.
+
Clicking on a hint reveals the lines of code that need to be changed. To see additional details about the issue, right-click on the detail and select *View details*.
+
You can make the changes needed and then click/select *Mark as Complete* or *Delete*  -- an save in the Java file.


== Resolving issues

Look at A's


== icons

get from email
